import React, { useState } from 'react';
import { 
  AlertTriangle, 
  ShieldAlert, 
  Filter, 
  Search, 
  Clock, 
  CheckCircle2, 
  Radio, 
  X, 
  PhoneCall, 
  MessageSquare, 
  BellRing, 
  Send, 
  UserCheck, 
  Cpu, 
  Layers, 
  ChevronRight,
  Sparkles,
  Volume2,
  FileCheck
} from 'lucide-react';
import { EarlyWarningAlert, AlertState, AlertStatus, RiskLevel } from '../types';
import { getAlertStateBadge, getRiskColor } from '../utils/formatters';

interface EarlyWarningCenterProps {
  alerts: EarlyWarningAlert[];
  onUpdateAlertStatus: (alertId: string, newStatus: AlertStatus) => void;
  onSelectZoneId?: (zoneId: string) => void;
}

export const EarlyWarningCenter: React.FC<EarlyWarningCenterProps> = ({
  alerts,
  onUpdateAlertStatus,
  onSelectZoneId
}) => {
  const [filterRisk, setFilterRisk] = useState<string>('All');
  const [filterStatus, setFilterStatus] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [selectedAlert, setSelectedAlert] = useState<EarlyWarningAlert | null>(null);
  const [activeLanguage, setActiveLanguage] = useState<'en' | 'as' | 'hi'>('en');
  const [isSimulatingAudio, setIsSimulatingAudio] = useState<boolean>(false);
  const [actionSuccessMsg, setActionSuccessMsg] = useState<string | null>(null);

  const filteredAlerts = alerts.filter(a => {
    const matchesRisk = filterRisk === 'All' || a.riskLevel === filterRisk;
    const matchesStatus = filterStatus === 'All' || 
      (filterStatus === 'Active' && (a.status === 'Active' || a.status === 'Under Review' || a.status === 'Validated')) ||
      (filterStatus === 'Resolved' && a.status === 'Resolved');
    const matchesSearch = searchQuery === '' || 
      a.location.toLowerCase().includes(searchQuery.toLowerCase()) || 
      a.trigger.toLowerCase().includes(searchQuery.toLowerCase()) ||
      a.id.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesRisk && matchesStatus && matchesSearch;
  });

  const handleAction = (status: AlertStatus, label: string) => {
    if (!selectedAlert) return;
    onUpdateAlertStatus(selectedAlert.id, status);
    setSelectedAlert({ ...selectedAlert, status });
    setActionSuccessMsg(`Status updated: Alert ${selectedAlert.id} is now marked as ${status}`);
    setTimeout(() => setActionSuccessMsg(null), 3000);
  };

  const handleSimulateIVR = () => {
    setIsSimulatingAudio(true);
    setTimeout(() => {
      setIsSimulatingAudio(false);
    }, 4000);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
      {/* Top Banner */}
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 p-6 rounded-2xl bg-gradient-to-r from-slate-900 via-[#130b20] to-slate-900 border border-red-500/30 shadow-2xl">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-bold uppercase tracking-wider bg-red-600 text-white animate-pulse">
              Early Warning Operations Desk
            </span>
            <span className="text-xs font-mono text-slate-400 hidden sm:inline">
              CAP-India Multilingual Gateway Active
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
            Early Warning Center & Dissemination Console
          </h1>
          <p className="text-xs sm:text-sm text-slate-300 max-w-2xl">
            Review algorithmic alerts generated by the AI Risk Prediction Engine, validate field trigger evidence, and dispatch life-saving multi-channel advisories.
          </p>
        </div>

        {/* Quick Summary Pill Counters */}
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 text-center">
            <div className="text-xl font-bold font-mono text-cyan-400">
              {alerts.filter(a => a.status !== 'Resolved').length}
            </div>
            <div className="text-[10px] text-slate-400 font-medium">Active Warnings</div>
          </div>
          <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 text-center">
            <div className="text-xl font-bold font-mono text-red-400">
              {alerts.filter(a => a.alertState === 'Critical' && a.status !== 'Resolved').length}
            </div>
            <div className="text-[10px] text-slate-400 font-medium">Critical Severity</div>
          </div>
          <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 text-center">
            <div className="text-xl font-bold font-mono text-emerald-400">
              {alerts.filter(a => a.status === 'Resolved').length}
            </div>
            <div className="text-[10px] text-slate-400 font-medium">Resolved</div>
          </div>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3 flex-wrap">
          {/* Search Box */}
          <div className="relative">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search alert ID, district, trigger..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9 pr-4 py-2 rounded-xl bg-slate-950 border border-slate-700 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-cyan-500 w-56 sm:w-64"
            />
            {searchQuery && (
              <button 
                onClick={() => setSearchQuery('')}
                className="absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            )}
          </div>

          {/* Risk Filter */}
          <div className="flex items-center gap-1 bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs">
            <span className="px-2 text-[11px] text-slate-400 font-medium hidden sm:inline">Risk:</span>
            {['All', 'HIGH', 'MEDIUM', 'LOW'].map(lvl => (
              <button
                key={lvl}
                onClick={() => setFilterRisk(lvl)}
                className={`px-2.5 py-1 rounded-lg text-xs font-semibold transition-colors ${
                  filterRisk === lvl
                    ? lvl === 'HIGH' ? 'bg-red-500 text-white'
                    : lvl === 'MEDIUM' ? 'bg-amber-500 text-slate-950'
                    : lvl === 'LOW' ? 'bg-emerald-500 text-slate-950'
                    : 'bg-cyan-500 text-slate-950'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {lvl}
              </button>
            ))}
          </div>

          {/* Status Filter */}
          <div className="flex items-center gap-1 bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs">
            <span className="px-2 text-[11px] text-slate-400 font-medium hidden sm:inline">Status:</span>
            {['All', 'Active', 'Resolved'].map(st => (
              <button
                key={st}
                onClick={() => setFilterStatus(st)}
                className={`px-2.5 py-1 rounded-lg text-xs font-semibold transition-colors ${
                  filterStatus === st
                    ? 'bg-blue-600 text-white'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {st}
              </button>
            ))}
          </div>
        </div>

        <div className="text-xs font-mono text-slate-400">
          Showing <strong className="text-white">{filteredAlerts.length}</strong> alerts
        </div>
      </div>

      {/* Alerts Feed List */}
      <div className="space-y-4">
        {filteredAlerts.length === 0 ? (
          <div className="p-12 text-center rounded-2xl bg-slate-900/60 border border-slate-800">
            <CheckCircle2 className="w-10 h-10 text-emerald-400 mx-auto mb-3" />
            <h3 className="text-base font-bold text-white">No Matching Alerts Found</h3>
            <p className="text-xs text-slate-400 mt-1">Try clearing filters or search queries.</p>
          </div>
        ) : (
          filteredAlerts.map(alert => {
            const badge = getAlertStateBadge(alert.alertState);
            const riskColor = getRiskColor(alert.riskLevel);
            const isCritical = alert.alertState === 'Critical';

            return (
              <div
                key={alert.id}
                id={`alert-card-${alert.id}`}
                onClick={() => setSelectedAlert(alert)}
                className={`p-5 rounded-2xl border transition-all cursor-pointer group shadow-lg ${
                  isCritical 
                    ? 'bg-gradient-to-r from-red-950/20 via-slate-900 to-slate-900 border-red-500/40 hover:border-red-500/70 shadow-red-950/20' 
                    : 'bg-slate-900/80 border-slate-800 hover:border-cyan-500/40'
                }`}
              >
                <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
                  {/* Left Column: Title & Trigger */}
                  <div className="space-y-2 flex-1">
                    <div className="flex items-center gap-2.5 flex-wrap">
                      <span className={`px-2.5 py-0.5 rounded text-[11px] font-black uppercase tracking-wider ${badge.bg}`}>
                        {alert.alertState}
                      </span>
                      <span className="text-sm font-bold text-white group-hover:text-cyan-300 transition-colors">
                        {alert.location}
                      </span>
                      <span className="text-xs font-mono text-slate-400">
                        {alert.id}
                      </span>
                      <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold border ${riskColor.badgeBg} ${riskColor.badgeText} ${riskColor.badgeBorder}`}>
                        Score: {alert.riskScore}/100
                      </span>
                    </div>

                    <p className="text-xs text-slate-300 font-medium">
                      <strong className="text-amber-400">Trigger:</strong> {alert.trigger}
                    </p>

                    <div className="flex items-center gap-4 text-xs text-slate-400 flex-wrap pt-1">
                      <span className="flex items-center gap-1 font-mono">
                        <Clock className="w-3.5 h-3.5 text-slate-400" />
                        {alert.timestamp}
                      </span>
                      <span className="flex items-center gap-1 font-mono">
                        <Cpu className="w-3.5 h-3.5 text-cyan-400" />
                        Model Confidence: <strong className="text-slate-200">{alert.aiConfidence}%</strong>
                      </span>
                      <span className="flex items-center gap-1">
                        <Radio className="w-3.5 h-3.5 text-blue-400" />
                        Status: <strong className="text-slate-200">{alert.status}</strong>
                      </span>
                    </div>
                  </div>

                  {/* Right Column: Channels & Details Button */}
                  <div className="flex items-center justify-between lg:justify-end gap-3 pt-3 lg:pt-0 border-t lg:border-t-0 border-slate-800">
                    <div className="flex items-center gap-1.5 text-slate-400">
                      {alert.disseminationChannels.map(ch => (
                        <span key={ch} className="px-2 py-0.5 rounded bg-slate-950 text-[10px] font-mono border border-slate-800">
                          {ch}
                        </span>
                      ))}
                    </div>

                    <button
                      id={`inspect-alert-${alert.id}`}
                      onClick={(e) => {
                        e.stopPropagation();
                        setSelectedAlert(alert);
                      }}
                      className="flex items-center gap-1 px-3 py-1.5 rounded-xl bg-slate-800 group-hover:bg-cyan-500 text-slate-200 group-hover:text-slate-950 text-xs font-bold transition-all shadow"
                    >
                      <span>Alert Details</span>
                      <ChevronRight className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* Detailed Alert Inspection Modal */}
      {selectedAlert && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
          <div className="relative w-full max-w-3xl rounded-2xl bg-slate-900 border border-slate-700 shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-150 my-8">
            {/* Modal Header */}
            <div className="p-5 bg-slate-950 border-b border-slate-800 flex items-start justify-between">
              <div>
                <div className="flex items-center gap-2">
                  <span className={`px-2.5 py-0.5 rounded text-xs font-black uppercase tracking-wider ${
                    selectedAlert.alertState === 'Critical' ? 'bg-red-600 text-white' : 'bg-amber-500 text-slate-950'
                  }`}>
                    {selectedAlert.alertState} WARNING
                  </span>
                  <span className="text-xs font-mono text-cyan-400 font-bold">
                    {selectedAlert.id}
                  </span>
                  <span className="text-xs font-mono px-2 py-0.5 rounded bg-slate-800 text-slate-300">
                    {selectedAlert.status}
                  </span>
                </div>
                <h2 className="text-xl font-bold text-white mt-1">
                  {selectedAlert.location}
                </h2>
                <p className="text-xs text-slate-400">
                  {selectedAlert.district}, {selectedAlert.state} • Issued {selectedAlert.timestamp}
                </p>
              </div>

              <button
                id="close-alert-modal-btn"
                onClick={() => setSelectedAlert(null)}
                className="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Content */}
            <div className="p-6 space-y-6 max-h-[75vh] overflow-y-auto">
              {actionSuccessMsg && (
                <div className="p-3 rounded-xl bg-emerald-950/60 border border-emerald-500/50 text-emerald-300 text-xs font-semibold flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  <span>{actionSuccessMsg}</span>
                </div>
              )}

              {/* Warning Summary Cards */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
                <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                  <div className="text-[11px] text-slate-400 font-medium">Risk Score</div>
                  <div className="text-xl font-bold font-mono text-red-400 mt-0.5">
                    {selectedAlert.riskScore}/100
                  </div>
                  <div className="text-[10px] text-slate-500">Level: {selectedAlert.riskLevel}</div>
                </div>

                <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                  <div className="text-[11px] text-slate-400 font-medium">Model Confidence</div>
                  <div className="text-xl font-bold font-mono text-cyan-300 mt-0.5">
                    {selectedAlert.aiConfidence}%
                  </div>
                  <div className="text-[10px] text-slate-500">Statistical certain.</div>
                </div>

                <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                  <div className="text-[11px] text-slate-400 font-medium">Pop. At Risk (Est.)</div>
                  <div className="text-xl font-bold font-mono text-white mt-0.5">
                    {selectedAlert.affectedPopulationEst.toLocaleString()}
                  </div>
                  <div className="text-[10px] text-slate-500">Habitations in path</div>
                </div>

                <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                  <div className="text-[11px] text-slate-400 font-medium">Lifelines Impacted</div>
                  <div className="text-xl font-bold font-mono text-amber-400 mt-0.5">
                    {selectedAlert.criticalInfrastructure.length}
                  </div>
                  <div className="text-[10px] text-slate-500">Highways / Bridges</div>
                </div>
              </div>

              {/* Trigger Conditions Diagnostics */}
              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-3">
                <div className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-2">
                  <Cpu className="w-4 h-4 text-cyan-400" />
                  <span>Physical & Environmental Trigger Conditions</span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                  <div className="flex items-center justify-between p-2.5 rounded-lg bg-slate-900 border border-slate-800">
                    <span className="text-slate-400">Precipitation Inflow:</span>
                    <span className="font-mono font-bold text-cyan-300">{selectedAlert.environmentalTriggers.rainfallRate}</span>
                  </div>
                  <div className="flex items-center justify-between p-2.5 rounded-lg bg-slate-900 border border-slate-800">
                    <span className="text-slate-400">Pore Saturation:</span>
                    <span className="font-mono font-bold text-amber-400">{selectedAlert.environmentalTriggers.soilSaturation}</span>
                  </div>
                  <div className="flex items-center justify-between p-2.5 rounded-lg bg-slate-900 border border-slate-800">
                    <span className="text-slate-400">Displacement Velocity:</span>
                    <span className="font-mono font-bold text-red-400">{selectedAlert.environmentalTriggers.slopeDisplacement}</span>
                  </div>
                  <div className="flex items-center justify-between p-2.5 rounded-lg bg-slate-900 border border-slate-800">
                    <span className="text-slate-400">Shear Stress Ratio:</span>
                    <span className="font-mono font-bold text-slate-200">{selectedAlert.environmentalTriggers.shearStressRatio}</span>
                  </div>
                </div>
              </div>

              {/* AI Decision-Support Recommendations */}
              <div className="p-4 rounded-xl bg-amber-950/20 border border-amber-500/30 space-y-2">
                <div className="flex items-center gap-2 text-xs font-bold text-amber-300">
                  <ShieldAlert className="w-4 h-4" />
                  <span>AI Decision-Support Recommendations</span>
                </div>
                <ul className="space-y-1.5 text-xs text-slate-200">
                  {selectedAlert.recommendedActions.map((rec, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-1.5 flex-shrink-0" />
                      <span>{rec}</span>
                    </li>
                  ))}
                </ul>
                <div className="text-[10px] text-amber-400/80 pt-1">
                  *Decision-support only: Not an automatic government executive decree. Requires authorized District Magistrate / DM Officer sign-off.
                </div>
              </div>

              {/* Multilingual Dissemination Preview (English, Assamese, Hindi) */}
              <div className="p-4 rounded-xl bg-[#09152e] border border-cyan-500/30 space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-xs font-bold text-cyan-300">
                    <MessageSquare className="w-4 h-4" />
                    <span>Multilingual Public Broadcast Preview (SMS / IVR / App)</span>
                  </div>

                  {/* Language Selector */}
                  <div className="flex items-center gap-1 bg-slate-950 p-1 rounded-lg border border-slate-800 text-xs">
                    <button
                      onClick={() => setActiveLanguage('en')}
                      className={`px-2 py-0.5 rounded font-semibold ${
                        activeLanguage === 'en' ? 'bg-cyan-500 text-slate-950' : 'text-slate-400 hover:text-white'
                      }`}
                    >
                      English
                    </button>
                    <button
                      onClick={() => setActiveLanguage('as')}
                      className={`px-2 py-0.5 rounded font-semibold ${
                        activeLanguage === 'as' ? 'bg-cyan-500 text-slate-950' : 'text-slate-400 hover:text-white'
                      }`}
                    >
                      অসমীয়া (Assamese)
                    </button>
                    <button
                      onClick={() => setActiveLanguage('hi')}
                      className={`px-2 py-0.5 rounded font-semibold ${
                        activeLanguage === 'hi' ? 'bg-cyan-500 text-slate-950' : 'text-slate-400 hover:text-white'
                      }`}
                    >
                      हिन्दी (Hindi)
                    </button>
                  </div>
                </div>

                <div className="p-3 rounded-lg bg-slate-950 border border-slate-800 text-xs text-slate-200 font-mono leading-relaxed">
                  {selectedAlert.multilingualAlert[activeLanguage]}
                </div>

                {/* IVR Voice Playback Simulation */}
                <div className="flex items-center justify-between pt-1">
                  <div className="flex items-center gap-2">
                    <button
                      onClick={handleSimulateIVR}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-cyan-300 transition-colors"
                    >
                      <Volume2 className={`w-3.5 h-3.5 ${isSimulatingAudio ? 'text-amber-400 animate-pulse' : 'text-cyan-400'}`} />
                      <span>{isSimulatingAudio ? 'Simulating IVR Voice Broadcast...' : 'Test IVR Audio Synthesis'}</span>
                    </button>
                    {isSimulatingAudio && (
                      <span className="text-[10px] text-amber-300 font-mono animate-pulse">
                        [Playing 16kHz audio beacon]
                      </span>
                    )}
                  </div>

                  <span className="text-[11px] text-slate-400 font-mono">
                    Gateway: National CAP Node #041
                  </span>
                </div>
              </div>
            </div>

            {/* Modal Footer: DM Officer Action Desk */}
            <div className="p-4 bg-slate-950 border-t border-slate-800 flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <UserCheck className="w-4 h-4 text-cyan-400" />
                <span className="text-xs font-bold text-white">DM Officer Human Validation Desk:</span>
              </div>

              <div className="flex items-center gap-2 flex-wrap">
                <button
                  id="hold-alert-btn"
                  onClick={() => handleAction('Under Review', 'Hold')}
                  className="px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold transition-colors"
                >
                  Hold for Field Verification
                </button>

                <button
                  id="resolve-alert-btn"
                  onClick={() => handleAction('Resolved', 'Resolve')}
                  className="px-3 py-2 rounded-xl bg-emerald-700/60 hover:bg-emerald-600 text-white text-xs font-semibold transition-colors"
                >
                  Mark as Resolved
                </button>

                <button
                  id="approve-dispatch-alert-btn"
                  onClick={() => handleAction('Dispatched', 'Dispatch')}
                  className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-red-600 hover:bg-red-500 text-white text-xs font-bold shadow-lg shadow-red-900/40 transition-colors"
                >
                  <Send className="w-3.5 h-3.5" />
                  <span>Approve & Disseminate Alert</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
